language: node_js
sudo: false
before_install:
  - npm install jasmine parse-server@acinader/parse-server#built-push-scaling
node_js:
 # - "4.5"
  - "6"

after_success:
  - bash <(curl -s https://codecov.io/bash)
